# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  #vmImage: 'vs2017-win2016'

jobs:
- job: Prepare

  steps:
  - task: oc-setup@2
    inputs:
      connectionType: 'OpenShift Connection Service'
      openshiftService: 'OCP Cluster 1'
      #version: 'https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz'
      version: '4.5.9'

  - bash: |
        echo "This is job Prepare. $(agent.builddirectory) $(Build.ArtifactStagingDirectory)
        oc new-project ${DEV_PROJECT_NAME}
        oc new-project ${TEST_PROJECT_NAME}
    name: CreateProjects
    continueOnError: true
    
  - bash: |
      echo "This is job Prepare. $(agent.builddirectory) $(Build.ArtifactStagingDirectory)"
      echo "$(Build.ArtifactStagingDirectory)"
      ls $(Build.ArtifactStagingDirectory)
      echo "$(agent.builddirectory)"
      ls $(agent.builddirectory)
      export PROJECT_NAME=`oc get ns ${DEV_PROJECT_NAME} -o name`
      echo "##vso[task.setvariable variable=DevProjectFoundName;isOutput=true]$PROJECT_NAME"
      echo "##vso[task.setvariable variable=TestProjectFoundName;isOutput=true]`oc get ns ${TEST_PROJECT_NAME} -o name`"
     
    name: CheckProjects

  - script: echo $(CheckProjects.DevProjectFoundName)
    name: echoDevProjectFoundName
  - script: echo $(CheckProjects.TestProjectFoundName)
    name: echoTestProjectFoundName

- job: Run
  variables:
    DevProjectName: $[ dependencies.Prepare.outputs['Prepare.CheckProjects.DevProjectFoundName'] ]

  steps:
  - task: oc-setup@2
    inputs:
      connectionType: 'OpenShift Connection Service'
      openshiftService: 'OCP Cluster 1'
      #version: 'https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz'
      version: '4.5.9'

  - script: echo $(DevProjectName)
    name: echoDevProjectName
  - bash: |
      echo "This is job Run. $(agent.builddirectory) $(Build.ArtifactStagingDirectory)"

      echo "Build: $(Build)"
      echo "agent: $(agent)"

      echo "$(Build.ArtifactStagingDirectory)"
      ls $(Build.ArtifactStagingDirectory)
      echo "$(agent.builddirectory)"
      ls $(agent.builddirectory)
      if [ -z "`oc get ns ${DEV_PROJECT_NAME} -o name`" ]
      then
            echo "${DEV_PROJECT_NAME} doesn't exists"
            echo "##vso[task.setvariable variable=DevProjectExists;isOutput=true]false"
      else
            echo "${DEV_PROJECT_NAME} exists"
            echo "##vso[task.setvariable variable=DevProjectExists;isOutput=true]true"
      fi
    name: CheckProjects

  - task: Maven@3
    name: MavenTest
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'test'
    enabled: false
  
  - task: Maven@3
    name: MavenPackage
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package -DskipTests -Popenshift'
    enabled: true

  - bash: |
      echo "This is job Run. $(agent.builddirectory) $(Build.ArtifactStagingDirectory)"

      echo "ArtifactStagingDirectory: $(Build.ArtifactStagingDirectory)"
      ls $(Build.ArtifactStagingDirectory)

      echo "builddirectory: $(agent.builddirectory)"
      ls $(agent.builddirectory)

      echo "Build.BinariesDirectory: $(Build.BinariesDirectory)"
      ls $(Build.BinariesDirectory)/*

      if [ -z "`oc get bc ${BUILD_NAME} -o name`" ]
      then
            echo "bc ${BUILD_NAME} doesn't exists"
            echo "##vso[task.setvariable variable=BuildConfigDoesntExists;isOutput=true]true"
      else
            echo "bc ${BUILD_NAME} exists"
            echo "##vso[task.setvariable variable=BuildConfigDoesntExists;isOutput=true]false"
      fi
    name: CheckBuildConfig

  - task: oc-cmd@2
    inputs:
      connectionType: 'OpenShift Connection Service'
      openshiftService: 'OCP Cluster 1'
      version: '4.5.9'
      uselocalOc: true
      cmd: 'new-build --name=$(BUILD_NAME) --image-stream=$(BUILD_IMAGE_STREAM) --binary -n $(DEV_PROJECT_NAME)'
      ignoreFlag: true
    #condition: eq('${{ variables['CheckBuildConfig.BuildConfigDoesntExists'] }}', true)
    condition: eq(variables['CheckBuildConfig.BuildConfigDoesntExists'], true)
  - task: oc-cmd@2
    inputs:
      connectionType: 'OpenShift Connection Service'
      openshiftService: 'OCP Cluster 1'
      version: '4.5.9'
      uselocalOc: true
      cmd: 'start-build $(BUILD_NAME) --from-file=$(Build.ArtifactStagingDirectory)/target/$(APP_NAME)-dev-$(POM_VERSION).jar --wait -n $(DEV_PROJECT_NAME)'



